version: '2'

services:
  spark_master:
    build: .

    command: ./start-master.sh

    entrypoint: /cassandra-configurator.sh

    environment:
      SPARK_HOME: /usr/local/spark
      SPARK_MASTER_OPTS: '-Dspark.driver.port=7001 -Dspark.fileserver.port=7002 -Dspark.broadcast.port=7003 -Dspark.replClassServer.port=7004 -Dspark.blockManager.port=7005 -Dspark.executor.port=7006 -Dspark.ui.port=4040 -Dspark.broadcast.factory=org.apache.spark.broadcast.HttpBroadcastFactory'
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 8080
      CASSANDRA_CONFIG: /etc/cassandra

    expose:
    - "4040"
    - "7000"
    - "7001"
    - "7002"
    - "7003"
    - "7004"
    - "7005"
    - "7006"
    - "7077"
    - "7199"
    - "8080"
    - "8081"
    - "8888"
    - "9042"
    - "9160"

    volumes:
    - "/var/lib/cassandra"