CREATE TABLE sparkassandra.us_flights (
  Id                INT PRIMARY KEY,
  Year              INT,
  Month             INT,
  DayOfWeek         INT,
  DepTime           text,
  CRSDepTime        INT,
  ArrTime           text,
  CRSArrTime        INT,
  UniqueCarrier     text,
  FlightNum         INT,
  TailNum           text,
  ActualElapsedTime text,
  CRSElapsedTime    INT,
  AirTime           text,
  ArrDelay          text,
  DepDelay          text,
  Origin            text,
  Dest              text,
  Distance          text,
  TaxiIn            text,
  TaxiOut           text,
  Cancelled         INT,
  CancellationCode  text,
  Diverted          INT,
  CarrierDelay      text,
  WeatherDelay      text,
  NASDelay          text,
  SecurityDelay     text,
  LateAircraftDelay text
);