version: '2'

networks:
  spark_cluster_nw:
    driver: overlay

services:
  cassandra_master:
    image: cassandra:3.9
    environment:
    - MAX_HEAP_SIZE=2048m
    - HEAP_NEWSIZE=100m
    networks:
     - spark_cluster_nw

  cassandra_node:
    image: cassandra:3.9
    environment:
    - CASSANDRA_SEEDS=cassandra_master
    - MAX_HEAP_SIZE=2048m
    - HEAP_NEWSIZE=100m
    depends_on:
    - cassandra_master
    networks:
     - spark_cluster_nw

  spark_master:
      build: .
      command: ./start-master.sh
      volumes:
      - ./jobs:/jobs
      ports:
      - 8080:8080 # web interface
      - 7077:7077 # spark interface to send jobs
      - 6066:6066 # REST interface
      - 4040:4040 # web UI
      environment:
      - "constraint:sparkport==http8080"
      networks:
       - spark_cluster_nw

  spark_worker_a:
    build: .
    command: ./start-worker.sh
    volumes:
    - ./jobs:/jobs
    ports:
    - 8081:8081
    depends_on:
    - spark_master
    networks:
     - spark_cluster_nw

  spark_worker_b:
     build: .
     command: ./start-worker.sh
     volumes:
     - ./jobs:/jobs
     depends_on:
     - spark_master
     networks:
      - spark_cluster_nw

  jupyter:
    build: ./pyspark-notebook
    ports:
    - 8890:8888 #web console
    environment:
    - "constraint:jupyterport==http8890"
    networks:
     - spark_cluster_nw
